/* Generated by Fetlang */
#include <stdio.h>
#include "core/include/chain.h"
#include "core/include/compatibility.h"
#include "core/include/error.h"
#include "core/include/fraction.h"
#include "core/include/fraction_math.h"
#include "core/include/typedefs.h"
int main(int argc, char* argv[]){
/* Initializing variables */
Fraction fetvar_1_belinda;
fetvar_1_belinda.num = 0;
fetvar_1_belinda.den = 1;
Fraction fetvar_2_gloria;
fetvar_2_gloria.num = 0;
fetvar_2_gloria.den = 1;
Chain fetvar_3_peter;
init_chain(&fetvar_3_peter);
Chain fetvar_4_rocky;
init_chain(&fetvar_4_rocky);

Fraction argc_fraction = construct_fraction(argc, 1);
Chain argv_chain;
init_chain(&argv_chain);for(int i=0;i<argc;i++){append_cstr_to_chain(&argv_chain, argv[i]); append_flink_to_chain(&argv_chain, construct_fraction(0,1));}
do{
fetvar_1_belinda=add_fractions(fetvar_1_belinda, construct_fraction(100, 1));

fetvar_2_gloria=add_fractions(fetvar_2_gloria, construct_fraction(1, 1));

while(!((compare_fractions(fetvar_1_belinda, fetvar_2_gloria)==-1))){
/* Chain literal initialization */
Chain temp_chain_16807;
init_chain(&temp_chain_16807);
append_cstr_to_chain(&temp_chain_16807, "");

clear_chain(&fetvar_3_peter); append_chain_to_chain(&fetvar_3_peter, temp_chain_16807);

/* Chain literal deconstruction */
clear_chain(&temp_chain_16807);

append_fraction_to_chain(&fetvar_3_peter, fetvar_1_belinda);

if(((compare_fractions(fetvar_1_belinda, fetvar_2_gloria)==0))){
/* Chain literal initialization */
Chain temp_chain_282475249;
init_chain(&temp_chain_282475249);
append_cstr_to_chain(&temp_chain_282475249, " bottle of beer on the wall, ");

clear_chain(&fetvar_4_rocky); append_chain_to_chain(&fetvar_4_rocky, temp_chain_282475249);

/* Chain literal deconstruction */
clear_chain(&temp_chain_282475249);

}
else{
}
append_chain_to_chain(&fetvar_3_peter, fetvar_4_rocky);

append_fraction_to_chain(&fetvar_3_peter, fetvar_1_belinda);

if(((compare_fractions(fetvar_1_belinda, fetvar_2_gloria)==0))){
/* Chain literal initialization */
Chain temp_chain_1622650073;
init_chain(&temp_chain_1622650073);
append_cstr_to_chain(&temp_chain_1622650073, " bottle of beer! Take one down, pass it around, ");

clear_chain(&fetvar_4_rocky); append_chain_to_chain(&fetvar_4_rocky, temp_chain_1622650073);

/* Chain literal deconstruction */
clear_chain(&temp_chain_1622650073);

}
else{
}
fetvar_1_belinda=subtract_fractions(fetvar_1_belinda, construct_fraction(1, 1));

append_chain_to_chain(&fetvar_3_peter, fetvar_4_rocky);

append_fraction_to_chain(&fetvar_3_peter, fetvar_1_belinda);

if(((compare_fractions(fetvar_1_belinda, fetvar_2_gloria)==0))){
/* Chain literal initialization */
Chain temp_chain_984943658;
init_chain(&temp_chain_984943658);
append_cstr_to_chain(&temp_chain_984943658, " bottle of beer on the wall!");

clear_chain(&fetvar_4_rocky);append_chain_to_chain(&fetvar_4_rocky, temp_chain_984943658);append_flink_to_chain(&fetvar_4_rocky, construct_fraction(10,1));;

/* Chain literal deconstruction */
clear_chain(&temp_chain_984943658);

}
else{
}
append_chain_to_chain(&fetvar_3_peter, fetvar_4_rocky);

/* Stream chain(lho) initialization */
Chain temp_lho_stream_chain_1144108930;
init_chain(&temp_lho_stream_chain_1144108930);
append_stream_to_chain(&temp_lho_stream_chain_1144108930, stdout);

clear_chain(&temp_lho_stream_chain_1144108930); append_chain_to_chain(&temp_lho_stream_chain_1144108930, fetvar_3_peter);

/* Stream chain deconstruction */
chain_to_stream(temp_lho_stream_chain_1144108930, stdout);
clear_chain(&temp_lho_stream_chain_1144108930);

}
}while(0);
clear_chain(&argv_chain);/* Deconstructing variables */
clear_chain(&fetvar_3_peter);
clear_chain(&fetvar_4_rocky);

/* Finished */
return 0;
}
