/* Generated by Fetlang */
#include <stdio.h>
#include "core/include/chain.h"
#include "core/include/compatibility.h"
#include "core/include/error.h"
#include "core/include/fraction.h"
#include "core/include/fraction_math.h"
#include "core/include/typedefs.h"
#include "assertiveness/include/assert.h"
int main(){
/* Initializing variables */
Fraction fetvar_1_0;
fetvar_1_0.num = 0;
fetvar_1_0.den = 1;
Fraction fetvar_2_1;
fetvar_2_1.num = 0;
fetvar_2_1.den = 1;
Fraction fetvar_3_2;
fetvar_3_2.num = 0;
fetvar_3_2.den = 1;
Fraction fetvar_4_3;
fetvar_4_3.num = 0;
fetvar_4_3.den = 1;
Fraction fetvar_5_4;
fetvar_5_4.num = 0;
fetvar_5_4.den = 1;
Fraction fetvar_6_5;
fetvar_6_5.num = 0;
fetvar_6_5.den = 1;
Fraction fetvar_7_6;
fetvar_7_6.num = 0;
fetvar_7_6.den = 1;
Fraction fetvar_8_7;
fetvar_8_7.num = 0;
fetvar_8_7.den = 1;
Fraction fetvar_9_alice;
fetvar_9_alice.num = 0;
fetvar_9_alice.den = 1;
Fraction fetvar_10_bob;
fetvar_10_bob.num = 0;
fetvar_10_bob.den = 1;
Chain fetvar_13_chain;
init_chain(&fetvar_13_chain);
Fraction fetvar_11_charlie;
fetvar_11_charlie.num = 0;
fetvar_11_charlie.den = 1;
Fraction fetvar_12_count;
fetvar_12_count.num = 0;
fetvar_12_count.den = 1;
FILE* fetvar_17_file = NULL;
Chain fetvar_16_filename;
init_chain(&fetvar_16_filename);
Chain fetvar_15_hello;
init_chain(&fetvar_15_hello);
Link* fetvar_14_reference = NULL;

do{
fetvar_1_0=add_fractions(fetvar_1_0, construct_fraction(0, 1));

fetvar_2_1=add_fractions(fetvar_2_1, construct_fraction(1, 1));

fetvar_3_2=add_fractions(fetvar_3_2, construct_fraction(2, 1));

fetvar_4_3=add_fractions(fetvar_4_3, construct_fraction(3, 1));

fetvar_5_4=add_fractions(fetvar_5_4, construct_fraction(4, 1));

fetvar_6_5=add_fractions(fetvar_6_5, construct_fraction(5, 1));

fetvar_7_6=add_fractions(fetvar_7_6, construct_fraction(6, 1));

fetvar_8_7=add_fractions(fetvar_8_7, construct_fraction(7, 1));

fetvar_9_alice=add_fractions(fetvar_9_alice, construct_fraction(5, 1));

fetvar_10_bob=add_fractions(fetvar_10_bob, construct_fraction(4, 1));

fetvar_11_charlie=add_fractions(fetvar_11_charlie, construct_fraction(4, 1));

fetlang_assert(compare_fractions(fetvar_9_alice, fetvar_10_bob) == 1, "assertion of dominance failed");;

fetlang_assert(!compare_fractions(fetvar_10_bob, fetvar_11_charlie), "assertion of equality between fractions failed");;

fetvar_9_alice=multiply_fractions(fetvar_9_alice, construct_fraction(0, 1));

fetvar_10_bob=multiply_fractions(fetvar_10_bob, construct_fraction(0, 1));

fetvar_11_charlie=multiply_fractions(fetvar_11_charlie, construct_fraction(0, 1));

fetvar_9_alice=subtract_fractions(fetvar_9_alice, construct_fraction(5, 1));

fetvar_10_bob=subtract_fractions(fetvar_10_bob, construct_fraction(4, 1));

fetvar_11_charlie=subtract_fractions(fetvar_11_charlie, construct_fraction(4, 1));

fetlang_assert(compare_fractions(fetvar_10_bob, fetvar_9_alice) == 1, "assertion of dominance failed");;

fetlang_assert(!compare_fractions(fetvar_10_bob, fetvar_11_charlie), "assertion of equality between fractions failed");;

fetvar_9_alice=multiply_fractions(fetvar_9_alice, construct_fraction(0, 1));

fetvar_10_bob=multiply_fractions(fetvar_10_bob, construct_fraction(0, 1));

fetvar_11_charlie=multiply_fractions(fetvar_11_charlie, construct_fraction(0, 1));

fetvar_9_alice=subtract_fractions(fetvar_9_alice, construct_fraction(5, 1));

fetvar_9_alice=multiply_fractions(fetvar_9_alice, construct_fraction(5, 1));

fetvar_10_bob=subtract_fractions(fetvar_10_bob, construct_fraction(25, 1));

fetlang_assert(!compare_fractions(fetvar_10_bob, fetvar_9_alice), "assertion of equality between fractions failed");;

fetvar_9_alice=multiply_fractions(fetvar_9_alice, construct_fraction(0, 1));

fetvar_10_bob=multiply_fractions(fetvar_10_bob, construct_fraction(0, 1));

fetvar_11_charlie=multiply_fractions(fetvar_11_charlie, construct_fraction(0, 1));

fetvar_12_count=add_fractions(fetvar_12_count, construct_fraction(0, 1));

/* Chain literal initialization */
Chain temp_chain_16807;
init_chain(&temp_chain_16807);
append_cstr_to_chain(&temp_chain_16807, "012");

clear_chain(&fetvar_13_chain); append_chain_to_chain(&fetvar_13_chain, temp_chain_16807);

/* Chain literal deconstruction */
clear_chain(&temp_chain_16807);

/* Bondage */
fetvar_14_reference = fetvar_13_chain.start;
while(fetvar_14_reference != NULL){
(*fetvar_14_reference).value=subtract_fractions((*fetvar_14_reference).value, construct_fraction(48, 1));

if(((compare_fractions(fetvar_12_count, fetvar_1_0)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_1_0), "assertion of equality between fractions failed");;

}
if(((compare_fractions(fetvar_12_count, fetvar_2_1)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_2_1), "assertion of equality between fractions failed");;

}
if(((compare_fractions(fetvar_12_count, fetvar_3_2)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_3_2), "assertion of equality between fractions failed");;

}
fetvar_12_count=add_fractions(fetvar_12_count, construct_fraction(1, 1));

fetvar_14_reference=fetvar_14_reference->next;}fetvar_14_reference=fetvar_13_chain.start;


/* Bondage */
fetvar_14_reference = fetvar_13_chain.start;
while(fetvar_14_reference != NULL){
if(((compare_fractions(fetvar_12_count, fetvar_1_0)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_1_0), "assertion of equality between fractions failed");;

}
if(((compare_fractions(fetvar_12_count, fetvar_2_1)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_2_1), "assertion of equality between fractions failed");;

}
if(((compare_fractions(fetvar_12_count, fetvar_3_2)==0))){
fetlang_assert(!compare_fractions((*fetvar_14_reference).value, fetvar_3_2), "assertion of equality between fractions failed");;

}
fetvar_12_count=add_fractions(fetvar_12_count, construct_fraction(1, 1));

fetvar_14_reference=fetvar_14_reference->next;}fetvar_14_reference=fetvar_13_chain.start;


/* Chain literal initialization */
Chain temp_chain_282475249;
init_chain(&temp_chain_282475249);
append_cstr_to_chain(&temp_chain_282475249, "Hello!");

clear_chain(&fetvar_15_hello); append_chain_to_chain(&fetvar_15_hello, temp_chain_282475249);

/* Chain literal deconstruction */
clear_chain(&temp_chain_282475249);

/* Chain literal initialization */
Chain temp_chain_1622650073;
init_chain(&temp_chain_1622650073);
append_cstr_to_chain(&temp_chain_1622650073, "test.txt");

clear_chain(&fetvar_16_filename); append_chain_to_chain(&fetvar_16_filename, temp_chain_1622650073);

/* Chain literal deconstruction */
clear_chain(&temp_chain_1622650073);

fetvar_17_file=open_file_as_stream(fetvar_16_filename);;

/* Safeword called */
break;
/* Stream chain(lho) initialization */
Chain temp_lho_stream_chain_984943658;
init_chain(&temp_lho_stream_chain_984943658);
append_stream_to_chain(&temp_lho_stream_chain_984943658, stderr);

/* Chain literal initialization */
Chain temp_chain_1144108930;
init_chain(&temp_chain_1144108930);
append_cstr_to_chain(&temp_chain_1144108930, "Safeword was not obeyed");

clear_chain(&temp_lho_stream_chain_984943658);append_chain_to_chain(&temp_lho_stream_chain_984943658, temp_chain_1144108930);append_flink_to_chain(&temp_lho_stream_chain_984943658, construct_fraction(10,1));;

/* Stream chain deconstruction */
chain_to_stream(temp_lho_stream_chain_984943658, stderr);
clear_chain(&temp_lho_stream_chain_984943658);

/* Chain literal deconstruction */
clear_chain(&temp_chain_1144108930);

fetlang_assert(!compare_fractions(fetvar_1_0, fetvar_2_1), "assertion of equality between fractions failed");;

}while(0);
/* Deconstructing variables */
clear_chain(&fetvar_13_chain);
fclose(fetvar_17_file);
clear_chain(&fetvar_16_filename);
clear_chain(&fetvar_15_hello);

/* Finished */
return 0;
}
